USE [MOBILE_COLLECTION]
GO

/****** Object:  StoredProcedure [dbo].[SP_ALDA_GET_PENUGASAN]    Script Date: 19/05/2026 14:05:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[SP_ALDA_GET_PENUGASAN]
(
    @BRANCH_ID     VARCHAR(10),
    @NOMOR_KONTRAK VARCHAR(50)  = '',
    @STATUS        VARCHAR(20)  = '',
    @PIC_NIK       VARCHAR(50)  = '',
    @DATE_FROM     DATETIME     = NULL,
    @DATE_TO       DATETIME     = NULL
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
          P.PENUGASAN_ID,
          P.CONTRACT_NO,
          P.SUBMISSION_ID,
          P.PIC_NIK,
          P.PIC_NAME,
          P.PIC_JABATAN,
          P.PIC_PILAR,
          P.PIC_LOKASI_FISIK,
          P.PIC_LOKASI_PEKERJAAN,
          P.PIC_AREA,
          P.PIC_CABANG,
          P.PIC_BRANCH_ID,
          ISNULL(P.AREA,            A.AREA)            AS AREA,
          ISNULL(P.BRANCH_NAME,     A.BRANCH_NAME)     AS BRANCH_NAME,
          ISNULL(P.PORTFOLIO,       A.PORTFOLIO)       AS PORTFOLIO,
          ISNULL(P.CUSTOMER_NAME,   A.CUSTOMER_NAME)   AS CUSTOMER_NAME,
          ISNULL(P.LEGAL_ADDRESS,   A.LEGAL_ADDRESS)   AS LEGAL_ADDRESS,
          ISNULL(P.CUSTOMER_PHONE,  A.CUSTOMER_PHONE)  AS CUSTOMER_PHONE,
          P.GO_LIVE_DATE,
          P.TANGGAL_BAYAR_ANGS_TERAKHIR,
          P.MERK_KENDARAAN,
          P.TYPE_KENDARAAN,
          P.TAHUN_KENDARAAN,
          P.CONTRACT_STATUS_SNAPSHOT,
          ISNULL(P.AMOUNT_TO_BE_PAID, A.AMOUNT_TO_BE_PAID) AS AMOUNT_TO_BE_PAID,
          A.CONTRACT_STATUS    AS MASTER_CONTRACT_STATUS,
          A.AMOUNT_TO_BE_PAID  AS MASTER_AMOUNT_TO_BE_PAID,
          P.STATUS             AS ASSIGN_STATUS,
          SR.STATUS_LABEL      AS ASSIGN_STATUS_LABEL,
          P.ASSIGN_VERSION,
          P.NOTES,
          P.CREATED_AT,
          P.CREATED_BY,
          P.UPDATED_AT,
          P.UPDATED_BY

    FROM  ALDA_PENUGASAN AS P WITH (NOLOCK)
        INNER JOIN MASTER_ALDA AS A WITH (NOLOCK)
            ON  A.NOMOR_KONTRAK = P.CONTRACT_NO
        LEFT  JOIN ALDA_STATUS_REF AS SR WITH (NOLOCK)
            ON  SR.STATUS_CODE  = P.STATUS
    WHERE A.BRANCH_ID    = @BRANCH_ID
      AND (@NOMOR_KONTRAK = '' OR P.CONTRACT_NO = @NOMOR_KONTRAK)
      AND (@STATUS        = '' OR P.STATUS       = @STATUS)
      AND (
            @PIC_NIK = ''
            OR REPLACE(P.PIC_NIK, '.', '') = REPLACE(@PIC_NIK, '.', '')
          )
      AND (@DATE_FROM IS NULL OR P.CREATED_AT >= @DATE_FROM)
      AND (@DATE_TO   IS NULL OR P.CREATED_AT  < DATEADD(DAY, 1, @DATE_TO))
    ORDER BY P.CREATED_AT DESC;

END;
GO


