USE [MOBILE_COLLECTION]
GO

/****** Object:  StoredProcedure [dbo].[SP_ALDA_TASKLIST_PENUGASAN] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[SP_ALDA_TASKLIST_PENUGASAN]
(
    @BRANCH_ID       VARCHAR(10),
    @NOMOR_KONTRAK   VARCHAR(50) = '',
    @CONTRACT_STATUS VARCHAR(20) = '',
    @PORTFOLIO       VARCHAR(20) = ''
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
          A.BRANCH_ID,
          A.BRANCH_NAME,
          A.AREA,
          A.PORTFOLIO,
          A.NOMOR_KONTRAK,
          A.CUSTOMER_NAME,
          A.GO_LIVE_DATE,
          A.TANGGAL_BAYAR_ANGS_TERAKHIR,
          A.MERK_KENDARAAN,
          A.TYPE_KENDARAAN,
          A.TAHUN_KENDARAAN,
          A.CUSTOMER_PHONE,
          A.LEGAL_ADDRESS,
          A.CONTRACT_STATUS,
          A.AMOUNT_TO_BE_PAID
    FROM  MASTER_ALDA AS A WITH (NOLOCK)
        LEFT JOIN ALDA_PENUGASAN AS P WITH (NOLOCK)
            ON  P.CONTRACT_NO = A.NOMOR_KONTRAK
        LEFT JOIN ALDA_STATUS_REF AS R WITH (NOLOCK)
            ON  R.STATUS_CODE = P.STATUS
    WHERE A.BRANCH_ID       = @BRANCH_ID
      AND (@NOMOR_KONTRAK   = '' OR A.NOMOR_KONTRAK   = @NOMOR_KONTRAK)
      AND (@CONTRACT_STATUS = '' OR A.CONTRACT_STATUS = @CONTRACT_STATUS)
      AND (@PORTFOLIO       = '' OR A.PORTFOLIO       = @PORTFOLIO)
      AND (
              P.CONTRACT_NO IS NULL
           OR P.STATUS      = 'CANCELLED'
           OR R.IS_FINAL    = 1
          )
    ORDER BY A.NOMOR_KONTRAK;

END;
GO