USE [MOBILE_COLLECTION]
GO

ALTER PROCEDURE [dbo].[SP_ALDA_PIC_TASKLIST_SUMMARY]
(
    @PIC_NIK VARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @normalised_nik VARCHAR(50);
    SET @normalised_nik = REPLACE(@PIC_NIK, '.', '');

    SELECT
        SUM(CASE WHEN [STATUS] = 'ASSIGNED'    THEN 1 ELSE 0 END) AS TUGAS_BARU,
        SUM(CASE WHEN [STATUS] = 'IN_PROGRESS' THEN 1 ELSE 0 END) AS TUGAS_PROSES,
        SUM(CASE WHEN [STATUS] = 'COMPLETED'   THEN 1 ELSE 0 END) AS TUGAS_BERJALAN
    FROM [dbo].[ALDA_PENUGASAN] WITH (NOLOCK)
    WHERE REPLACE([PIC_NIK], '.', '') = @normalised_nik;

END;
GO