USE [MOBILE_COLLECTION]
GO

/****** Object:  StoredProcedure [dbo].[SP_ALDA_DROPDOWN_PIC]    Script Date: 19/05/2026 14:05:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[SP_ALDA_DROPDOWN_PIC]
(@BRANCH_ID VARCHAR(10))

AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        NIK          AS [VALUE],
        NAMA         AS [DATA_PIC],
        JABATAN      AS [JABATAN],
        LOKASI_FISIK AS [LOKASI]
    FROM MASTER_ALDA_PIC
    WHERE BRANCH_ID = @BRANCH_ID;

END;
GO