USE [MOBILE_COLLECTION]
GO

/****** Object:  Table [dbo].[ALDA_PENUGASAN]    Script Date: 19/05/2026 14:02:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ALDA_PENUGASAN](
	[PENUGASAN_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CONTRACT_NO] [varchar](50) NOT NULL,
	[SUBMISSION_ID] [bigint] NULL,
	[STATUS] [varchar](20) NOT NULL,
	[ASSIGN_VERSION] [int] NOT NULL,
	[NOTES] [varchar](500) NULL,
	[PIC_NIK] [varchar](50) NOT NULL,
	[PIC_NAME] [varchar](200) NOT NULL,
	[PIC_JABATAN] [varchar](100) NULL,
	[PIC_PILAR] [varchar](100) NULL,
	[PIC_LOKASI_FISIK] [varchar](100) NULL,
	[PIC_LOKASI_PEKERJAAN] [varchar](100) NULL,
	[PIC_AREA] [varchar](100) NULL,
	[PIC_CABANG] [varchar](100) NULL,
	[PIC_BRANCH_ID] [varchar](10) NULL,
	[AREA] [varchar](50) NULL,
	[BRANCH_ID] [varchar](20) NULL,
	[BRANCH_NAME] [varchar](200) NULL,
	[PORTFOLIO] [varchar](20) NULL,
	[CUSTOMER_NAME] [varchar](300) NULL,
	[LEGAL_ADDRESS] [varchar](max) NULL,
	[CUSTOMER_PHONE] [varchar](50) NULL,
	[GO_LIVE_DATE] [datetime] NULL,
	[TANGGAL_BAYAR_ANGS_TERAKHIR] [datetime] NULL,
	[MERK_KENDARAAN] [varchar](100) NULL,
	[TYPE_KENDARAAN] [varchar](200) NULL,
	[TAHUN_KENDARAAN] [int] NULL,
	[CONTRACT_STATUS_SNAPSHOT] [varchar](50) NULL,
	[AMOUNT_TO_BE_PAID] [decimal](18, 2) NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[CREATED_BY] [varchar](200) NOT NULL,
	[UPDATED_AT] [datetime] NULL,
	[UPDATED_BY] [varchar](200) NULL,
 CONSTRAINT [PK_ALDA_PENUGASAN] PRIMARY KEY CLUSTERED 
(
	[PENUGASAN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_ALDA_PENUGASAN_CONTRACT] UNIQUE NONCLUSTERED 
(
	[CONTRACT_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[ALDA_PENUGASAN] ADD  CONSTRAINT [DF_ALDA_PENUGASAN_STATUS]  DEFAULT ('ASSIGNED') FOR [STATUS]
GO

ALTER TABLE [dbo].[ALDA_PENUGASAN] ADD  CONSTRAINT [DF_ALDA_PENUGASAN_VERSION]  DEFAULT ((1)) FOR [ASSIGN_VERSION]
GO

ALTER TABLE [dbo].[ALDA_PENUGASAN] ADD  CONSTRAINT [DF_ALDA_PENUGASAN_CREATED_AT]  DEFAULT (getdate()) FOR [CREATED_AT]
GO

ALTER TABLE [dbo].[ALDA_PENUGASAN]  WITH CHECK ADD  CONSTRAINT [CK_ALDA_PENUGASAN_STATUS] CHECK  (([STATUS]='CANCELLED' OR [STATUS]='COMPLETED' OR [STATUS]='IN_PROGRESS' OR [STATUS]='ASSIGNED'))
GO

ALTER TABLE [dbo].[ALDA_PENUGASAN] CHECK CONSTRAINT [CK_ALDA_PENUGASAN_STATUS]
GO