USE [MOBILE_COLLECTION]
GO

/****** Object:  Table [dbo].[ALDA_STATUS_REF]    Script Date: 19/05/2026 14:03:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ALDA_STATUS_REF](
	[STATUS_CODE] [varchar](20) NOT NULL,
	[STATUS_LABEL] [varchar](100) NOT NULL,
	[DESCRIPTION] [varchar](300) NULL,
	[IS_FINAL] [bit] NOT NULL,
	[SORT_ORDER] [int] NOT NULL,
	[IS_ACTIVE] [bit] NOT NULL,
 CONSTRAINT [PK_ALDA_STATUS_REF] PRIMARY KEY CLUSTERED 
(
	[STATUS_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ALDA_STATUS_REF] ADD  CONSTRAINT [DF_ALDA_STATUS_FINAL]  DEFAULT ((0)) FOR [IS_FINAL]
GO

ALTER TABLE [dbo].[ALDA_STATUS_REF] ADD  CONSTRAINT [DF_ALDA_STATUS_SORT]  DEFAULT ((0)) FOR [SORT_ORDER]
GO

ALTER TABLE [dbo].[ALDA_STATUS_REF] ADD  CONSTRAINT [DF_ALDA_STATUS_ACTIVE]  DEFAULT ((1)) FOR [IS_ACTIVE]
GO