USE [MOBILE_COLLECTION]
GO

/****** Object:  Table [dbo].[MASTER_ALDA_PIC]    Script Date: 19/05/2026 14:03:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MASTER_ALDA_PIC](
	[AREA] [varchar](100) NOT NULL,
	[CABANG] [varchar](100) NOT NULL,
	[BRANCH_ID] [varchar](10) NOT NULL,
	[NIK] [varchar](50) NOT NULL,
	[NAMA] [varchar](200) NOT NULL,
	[JABATAN] [varchar](100) NOT NULL,
	[PILAR] [varchar](100) NULL,
	[LOKASI_FISIK] [varchar](100) NULL,
	[LOKASI_PEKERJAAN] [varchar](100) NULL,
	[IS_ACTIVE] [bit] NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MASTER_ALDA_PIC] ADD  
	CONSTRAINT [DF_MASTER_ALDA_PIC_IS_ACTIVE]  DEFAULT ((0)) FOR [IS_ACTIVE]

GO