USE [MOBILE_COLLECTION]
GO

/****** Object:  Table [dbo].[ALDA_PENUGASAN_HISTORY]    Script Date: 19/05/2026 14:02:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ALDA_PENUGASAN_HISTORY](
	[HISTORY_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PENUGASAN_ID] [bigint] NOT NULL,
	[CONTRACT_NO] [varchar](50) NOT NULL,
	[CHANGE_TYPE] [varchar](20) NOT NULL,
	[CHANGE_REASON] [varchar](500) NULL,
	[CHANGED_AT] [datetime] NOT NULL,
	[CHANGED_BY] [varchar](200) NOT NULL,
	[STATUS_BEFORE] [varchar](20) NOT NULL,
	[STATUS_AFTER] [varchar](20) NOT NULL,
	[ASSIGN_VERSION_BEFORE] [int] NULL,
	[ASSIGN_VERSION_AFTER] [int] NULL,
	[PIC_NIK_BEFORE] [varchar](50) NOT NULL,
	[PIC_NAME_BEFORE] [varchar](200) NOT NULL,
	[PIC_JABATAN_BEFORE] [varchar](100) NULL,
	[PIC_PILAR_BEFORE] [varchar](100) NULL,
	[PIC_LOKASI_FISIK_BEFORE] [varchar](100) NULL,
	[PIC_LOKASI_PEKERJAAN_BEFORE] [varchar](100) NULL,
	[PIC_AREA_BEFORE] [varchar](100) NULL,
	[PIC_CABANG_BEFORE] [varchar](100) NULL,
	[PIC_NIK_AFTER] [varchar](50) NULL,
	[PIC_NAME_AFTER] [varchar](200) NULL,
	[PIC_JABATAN_AFTER] [varchar](100) NULL,
	[PIC_PILAR_AFTER] [varchar](100) NULL,
	[PIC_LOKASI_FISIK_AFTER] [varchar](100) NULL,
	[PIC_LOKASI_PEKERJAAN_AFTER] [varchar](100) NULL,
	[PIC_AREA_AFTER] [varchar](100) NULL,
	[PIC_CABANG_AFTER] [varchar](100) NULL,
	[CONTRACT_STATUS_SNAPSHOT] [varchar](50) NULL,
	[AMOUNT_TO_BE_PAID] [decimal](18, 2) NULL,
 CONSTRAINT [PK_ALDA_PENUGASAN_HISTORY] PRIMARY KEY CLUSTERED 
(
	[HISTORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ALDA_PENUGASAN_HISTORY] ADD  CONSTRAINT [DF_ALDA_HISTORY_CHANGED_AT]  DEFAULT (getdate()) FOR [CHANGED_AT]
GO

ALTER TABLE [dbo].[ALDA_PENUGASAN_HISTORY]  WITH CHECK ADD  CONSTRAINT [CK_HISTORY_CHANGE_TYPE] CHECK  (([CHANGE_TYPE]='CANCEL' OR [CHANGE_TYPE]='STATUS_CHANGE' OR [CHANGE_TYPE]='REASSIGN'))
GO

ALTER TABLE [dbo].[ALDA_PENUGASAN_HISTORY] CHECK CONSTRAINT [CK_HISTORY_CHANGE_TYPE]
GO